#!/usr/bin/env python3
"""Snapshot the per-launch layer verification into the repo.

`~/callisto_swap.jsonl` is append-only, tens of MB, and lives outside the repo,
so a claim like "77/77 resolvers were served" is unverifiable later unless it
is extracted. This walks the journal, groups it into game starts (the app opens
the log from ~5 processes per launch), and pairs each group in order with a
line from `~/callisto_launches.log`.

The pairing is POSITIONAL: the Nth-from-last journal group is the Nth-from-last
launch line. It holds only while both files are append-only and no launch
bypassed sync (which would add a journal group with no log line). The overlay
flags printed per group are read from the journal itself, so a mismatch against
the log line's switches is visible and is the check that the pairing is sound.

Usage:  dev/ab_launch_audit.py [N]      # last N launches, default 8
"""
import json, os, re, sys
from collections import Counter

JS = os.path.expanduser("~/callisto_swap.jsonl")
LG = os.path.expanduser("~/callisto_launches.log")
n_want = int(sys.argv[1]) if len(sys.argv) > 1 else 8

opens = []
with open(JS, errors="replace") as f:
    for i, line in enumerate(f):
        if '"ev":"log_open"' in line:
            opens.append(i)
groups = []                      # a launch spawns several processes in a burst
for i in opens:
    if groups and i - groups[-1][-1] < 200:
        groups[-1].append(i)
    else:
        groups.append([i])
starts = [g[0] for g in groups] + [10 ** 9]

launches = [l.rstrip("\n") for l in open(LG) if l.strip()]
sel = list(range(max(0, len(groups) - n_want), len(groups)))

rows = []
with open(JS, errors="replace") as f:
    lines = f.readlines()
for gi in sel:
    lo, hi = starts[gi], starts[gi + 1]
    seg = lines[lo:hi]
    hits, ids, rej, ov, ser = 0, set(), 0, {}, []
    for s in seg:
        if '"swap":"HIT"' in s:
            hits += 1
            m = re.search(r'"id":"([^"]+)"', s)
            if m:
                ids.add(m.group(1))
        if "ser_reject" in s:
            rej += 1
        if '"ev":"overlay"' in s:
            d = json.loads(s)
            ov[d["name"]] = d["enabled"]
        if '"ev":"ser"' in s and '"action"' in s:
            d = json.loads(s)
            ser.append("%s/%s" % (d.get("action"), d.get("reason")))
    kinds = Counter(i.rsplit(".", 1)[1] for i in ids if "." in i)
    rows.append((gi, len(seg), hits, kinds, rej, ov, ser))

# pair positionally with the tail of the launch log
pairs = list(zip(launches[-len(rows):], rows)) if len(launches) >= len(rows) else []
print("# Launch audit -- generated by dev/ab_launch_audit.py\n")
for lg, (gi, nl, hits, kinds, rej, ov, ser) in pairs:
    ts = lg.split()[0]
    cfg = " ".join(w for w in lg.split()[1:]
                   if w.split("=")[0] in ("tier", "skinspec", "skin_sha", "ptq",
                                          "ser", "cache", "payload", "skin"))
    print("## %s" % ts)
    print("    %s" % cfg)
    print("    journal lines %d, total HITs %d, ser_reject %d" % (nl, hits, rej))
    print("    unique swapped modules: %s"
          % (", ".join("%s x%d" % (k, v) for k, v in sorted(kinds.items())) or "none"))
    print("    overlays enabled: %s"
          % (", ".join(k for k, v in ov.items() if v) or "NONE (bit-exact vanilla)"))
    if ser:
        print("    ser: %s" % "; ".join(sorted(set(ser))))
    print()
